services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Datos internos de Dockge
      - ./config/infra/dockge/data:/app/data
      # Directorio de Stacks (IMPORTANTE: ruta absoluta)
      - /home/daniel/daniel-homelab-core/stacks:/opt/stacks
    environment:
      # Indica a Dockge d√≥nde encontrar los stacks
      - DOCKGE_STACKS_DIR=/opt/stacks

networks:
  default:
    name: homelab-net
