services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=homelab-net"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--api=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
    networks:
      - default

  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    restart: unless-stopped
    ports:
      - "3552:3552"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/daniel/daniel-homelab/config/infra/arcane/data:/app/data
      - /home/daniel/daniel-homelab/stacks:/app/data/projects
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://localhost:3552
      - ENCRYPTION_KEY=fd2bafe48def8be127822c5da530b60dae71f81c652cca9d765bcb91c731fe06
      - JWT_SECRET=2a8b2f203969c2ca6308e4e73598b9f5205c0bda1d27b1b0e2d0659548cd27e7
      - DATABASE_URL=file:data/arcane.db?_pragma=journal_mode(WAL)&_pragma=busy_timeout(2500)&_txlock=immediate
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.arcane.rule=Host(`arcane.lab`)"
      - "traefik.http.routers.arcane.entrypoints=web"

  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    ports:
      - 8080:8080
    volumes:
      - /home/daniel/daniel-homelab/config/infra/dashy/user-data:/app/user-data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashy.rule=Host(`dashy.lab`)"
      - "traefik.http.routers.dashy.entrypoints=web"

networks:
  default:
    name: homelab-net
