services:
  arcane:
    image: ghcr.io/getarcaneapp/arcane:latest
    container_name: arcane
    restart: unless-stopped
    ports:
      - "3552:3552"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/daniel/daniel-homelab/config/infra/arcane/data:/app/data
      - /home/daniel/daniel-homelab/stacks:/app/data/projects
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://localhost:3552
      - ENCRYPTION_KEY=fd2bafe48def8be127822c5da530b60dae71f81c652cca9d765bcb91c731fe06
      - JWT_SECRET=2a8b2f203969c2ca6308e4e73598b9f5205c0bda1d27b1b0e2d0659548cd27e7
      - DATABASE_URL=file:data/arcane.db?_pragma=journal_mode(WAL)&_pragma=busy_timeout(2500)&_txlock=immediate

networks:
  default:
    name: homelab-net
