services:
  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    ports:
      - 8443:8443
    volumes:
      - /home/daniel/daniel-homelab/config/dev/code-server:/config
      - /home/daniel/daniel-homelab/workspace:/workspace
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - PASSWORD=yourpassword  # Cambia por una contrase√±a segura
    restart: unless-stopped
    networks:
      - homelab-net