http:
  routers:
    api:
      rule: "Host(`traefik.lab`)"
      service: api@internal
    arcane:
      rule: "Host(`arcane.lab`)"
      service: arcane
    dashy:
      rule: "Host(`dashy.lab`)"
      service: dashy
  services:
    arcane:
      loadBalancer:
        servers:
          - url: "http://arcane:3552"
    dashy:
      loadBalancer:
        servers:
          - url: "http://dashy:8080"

providers:
  file:
    filename: /etc/traefik/traefik.yml