http:
  routers:
    api:
      rule: "Host(`traefik.localhost`)"
      service: api@internal
      middlewares:
        - auth
  middlewares:
    auth:
      basicAuth:
        users:
          - 1000:1000

providers:
  docker:
    exposedByDefault: false