services:
  filebrowser:
    image: hurlenko/filebrowser:latest
    container_name: filebrowser
    environment:
      - FB_BASE_URL=/filebrowser   
      - PUID=1000
      - PGID=1000                 
      - TZ=America/Bogota
    ports:
      - 8090:8080
    volumes:
      - /home/daniel/daniel-homelab-core:/data
      - /home/daniel/daniel-homelab-core/config/management/filebrowser:/config
    restart: unless-stopped
networks: {}
